### ISSUE TITLE
sublime text

### ISSUE THREAD

**Issue by pseidemann** [jglovier/fizzy#4]
hello,
any chance that this gets ported to sublime text/textmate?
I really like this theme and would love to use it with another editor as well.

not sure but maybe this could help porting: http://tmtheme-editor.herokuapp.com/

**Comment by jglovier** [comment]
Sorry, it turns out I wasn't even watching my own repo! :confounded: 

Yeah, this is a great idea. I wanted to initially, but I never created a theme for ST2 before, and when i looked into it it looked like a giant pain in the ass. I'll check out that resource you shared and see if it makes this simpler.

Going to close for now, since this repo is specifically for the Atom theme.
